<？php

定义（'BOT_TOKEN'，'903748315:AAGli3uu1ZLFQ4jcnqnkQk017l1p1faY-ZA）; 

函数 checkTelegramAuthorization（$ auth_data）{
  $ check_hash = $ auth_data [ 'hash' ];
  unset（$ auth_data [ 'hash' ]）;
  $ data_check_arr = [];
  foreach（$ auth_data  as  $ key => $ value）{
    $ data_check_arr [] = $键。'='。$值 ;
  }
  排序（$ data_check_arr）;
  $ data_check_string =爆破（ “ \ n”， $ data_check_arr）;
  $ secret_key =哈希（ 'sha256'， BOT_TOKEN， true）;
  $ hash = hash_hmac（ 'sha256'， $ data_check_string， $ secret_key）;
  if（strcmp（$ hash，$ check_hash）！== 0）{
    抛出 新的 异常（“数据不是来自电报”）；
  }
  如果（（time（）- $ auth_data [ 'auth_date' ]）> 86400）{
    抛出 新 异常（“数据已过时”）；
  }
  返回 $ auth_data ;
}

函数 saveTelegramUserData（$ auth_data）{
  $ auth_data_json = json_encode（ $ auth_data）;
  setcookie（'tg_user'，$ auth_data_json）;
}


尝试 {
  $ auth_data = checkTelegramAuthorization（ $ _GET）;
  saveTelegramUserData（$ auth_data）;
} catch（例外 $ e）{
  die（$ e- > getMessage（））;
}

标头（“位置：login_example.php”）；

？>
